### ISSUE TITLE
help to make games

### ISSUE THREAD

**Issue by ghost** [Le36/Chip8-emulator#1]
Hi

I'm starting to make my own chip-8 emulator in C#.
It will be only very basic so not like your project.

I wanted to try to write my own games but I haveno idea where to even start!
Your emulator seems to be a great working place to make roms. 

Is it possible to get in contact with you for questions? I think nobody made a chip-8 emulator that has so cool features!
Did you ever made your own games using chip-8?

Thanks in advance!
Jessica

**Comment by Le36** [comment]
Hey, you should check Octo.

[https://github.com/JohnEarnest/Octo](https://github.com/JohnEarnest/Octo)

**Comment by ghost** [comment]
Is there a way to make games like they did in the 70s? (By only using the opcodes)
And how exactly to do this?

I use your emulator but I don't know how to make a game.
Did you ever tried this?

Thx
